services:
  cache:
    container_name: "cache"
    image: "docker.io/library/redis:7.4"
    ports:
      - target: 6379
        published: 6379
    restart: unless-stopped
  rmq:
    container_name: "rmq"
    image: "docker.io/library/rabbitmq:3.13-management"
    environment:
      RABBITMQ_DEFAULT_USER: "svck"
      RABBITMQ_DEFAULT_PASS: "Password123"
    volumes:
      - "apphost-rmq-data:/var/lib/rabbitmq"
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672
    restart: unless-stopped
  pg:
    container_name: "pg"
    image: "docker.io/library/postgres:16.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "svck"
      POSTGRES_PASSWORD: "Password123"
    volumes:
      - "apphost-pg-data:/var/lib/postgresql/data"
    ports:
      - target: 5432
        published: 5432
    restart: unless-stopped
  clickhouse:
    container_name: "clickhouse"
    image: "clickhouse/clickhouse-server:latest"
    environment:
      CLICKHOUSE_USER: "svck"
      CLICKHOUSE_PASSWORD: "Password123"
      CLICKHOUSE_DB: "svck"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - "clickhouse-data:/var/lib/clickhouse"
      - "logs:/var/log/clickhouse-server"
    ports:
      - target: 8123
        published: 8123
      - target: 9000
        published: 9000
    restart: unless-stopped
volumes:
  apphost-rmq-data: { }
  apphost-pg-data: { }
  clickhouse-data: { }
  logs: { }
